[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rna_mining-backend"
version = "0.1.0"
description = "Backend de Python configurado dinámicamente"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.110.0","uvicorn[standard]>=0.28.0"
]
